# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 743)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 150, 411, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_name_file = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_name_file.setMaximumSize(QtCore.QSize(137, 16777215))
        self.txt_name_file.setObjectName("txt_name_file")
        self.horizontalLayout.addWidget(self.txt_name_file, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lbl_name_file = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_name_file.setObjectName("lbl_name_file")
        self.horizontalLayout.addWidget(self.lbl_name_file, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txt_write = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_write.setObjectName("txt_write")
        self.horizontalLayout_4.addWidget(self.txt_write, 0, QtCore.Qt.AlignHCenter)
        self.lbl_write = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_write.setObjectName("lbl_write")
        self.horizontalLayout_4.addWidget(self.lbl_write, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txt_line = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_line.setObjectName("txt_line")
        self.horizontalLayout_6.addWidget(self.txt_line, 0, QtCore.Qt.AlignHCenter)
        self.lbl_lines = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_lines.setObjectName("lbl_lines")
        self.horizontalLayout_6.addWidget(self.lbl_lines, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.btn_analize = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_analize.setObjectName("btn_analize")
        self.verticalLayout.addWidget(self.btn_analize, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_vocals = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_vocals.setObjectName("lbl_vocals")
        self.verticalLayout_2.addWidget(self.lbl_vocals, 0, QtCore.Qt.AlignHCenter)
        self.txt_vocals = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.txt_vocals.setEnabled(True)
        self.txt_vocals.setObjectName("txt_vocals")
        self.verticalLayout_2.addWidget(self.txt_vocals, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_consonants = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_consonants.setObjectName("lbl_consonants")
        self.verticalLayout_3.addWidget(self.lbl_consonants, 0, QtCore.Qt.AlignHCenter)
        self.txt_consonants = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.txt_consonants.setObjectName("txt_consonants")
        self.verticalLayout_3.addWidget(self.txt_consonants, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.btn_analize.clicked.connect(self.analizar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.txt_name_file.setToolTip(_translate("Dialog", "<html><head/><body><p>l</p><p><br/></p></body></html>"))
        self.lbl_name_file.setText(_translate("Dialog", "Nombre del archivo"))
        self.lbl_write.setText(_translate("Dialog", "Texto a escribir"))
        self.lbl_lines.setText(_translate("Dialog", "Número de líneas del archivo"))
        self.btn_analize.setText(_translate("Dialog", "Analizar"))
        self.lbl_vocals.setText(_translate("Dialog", "Número de vocales"))
        self.lbl_consonants.setText(_translate("Dialog", "Número de consonantes"))

    def analizar(self):
    # Obtener texto y nombre de archivo
        nombre_archivo = self.txt_name_file.text().strip()
        texto = self.txt_write.text().strip().lower()

    # Verificar que haya texto y nombre de archivo
        if not nombre_archivo or not texto:
            QtWidgets.QMessageBox.warning(None, "Advertencia", "Debes escribir un nombre de archivo y texto.")
            return
    # Guardar el texto en el archivo    
        try:
            with open(nombre_archivo + ".txt", "w", encoding="utf-8") as f:
                lines= int(self.txt_line.text())
                for i in range(lines):
                    f.write(texto)
                    f.write("\n")
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", f"No se pudo guardar el archivo:\n{e}")
            return

    # Contar vocales y consonantes
        vocales = 'aeiouáéíóú'
        consonantes = 'bcdfghjklmnñpqrstvwxyz'
    
        num_vocales = sum(1 for c in texto if c in vocales)
        num_consonantes = sum(1 for c in texto if c in consonantes)

    # Mostrar resultados
        self.txt_vocals.setPlainText(str(num_vocales))
        self.txt_consonants.setPlainText(str(num_consonantes))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
